### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by Hxnter999** [extremecoders-re/python-snippet-decompiler#1]
Ive used this before and it worked great but now when I provide a .pyc file to it it just runs and nothing happens, i opened cmd, i ran python-snippet-decompiler.exe mypycfile.pyc and it just returned.

**Comment by extremecoders-re** [comment]
Is the pyc file from Python 3.11?

If not it should be a bug.

**Comment by Hun7er999** [comment]
Yep 311
