### ISSUE TITLE
Tool dont open : 

### ISSUE THREAD

**Issue by reactiver001** [extremecoders-re/python-snippet-decompiler#3]
Hello i try to use version Gui but dont work for me . I try some files and the tool window never opens, if I try with: pydisasm -F bytes . (works) but in tool (ui) mode it doesn't work. Any idea what the problem ?

![error_bug](https://github.com/extremecoders-re/python-snippet-decompiler/assets/46209343/6ac47b4e-7e5c-4066-9801-5c53c1cfab6f)

**Comment by extremecoders-re** [comment]
Is that pyc from Python 3.11 or 3.12. If so, it is unsupported at the moment.

**Comment by reactiver001** [comment]
Hello , its Python 3.9 my file .pyc

**Comment by extremecoders-re** [comment]
It should be a bug in that case. If you can upload the pyc, will be helpful to debug the issue.

**Comment by reactiver001** [comment]
Possible send me your email or something , because is private files. Thanks

**Comment by extremecoders-re** [comment]
The email id is on the GitHub profile

**Comment by extremecoders-re** [comment]
As communicated over email make sure to use the precompiled binaries. I think you are compiling your own which is fine, but it must be missing the python libraries and the tool won't run without it.

https://github.com/extremecoders-re/python-snippet-decompiler/releases

**Comment by reactiver001** [comment]
Hey , when you have time , please check your email , thanks for support

**Comment by reactiver001** [comment]
If anyone have the same problem, solution is :  right_flex.AddItem(button_panel, 0, 3, false)  ( layout issue, If the buttons are not showing)

**Comment by reactiver001** [comment]
When you have time , please check your email , thanks for all

**Comment by otodak** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Dyeniz72, @hakeemullahjan, @amintajy2, @ValentinBTC, @kotrird, @Borodabass, @3m4r5, @xiashali, @Tasha-Mia, @artivilla, @Abbey151998, @SHA888, @matagus, @blablainvest, @hugo-k-m, @Annie2022, @mariyakovenko, @byrd10, @fbiiapabo3, @Ngdxjj, @AnnaStark1, @FriedWagyu, @nurkeld1, @kejianlin, @koltci, @samannavaie, @tafrihonlinewebmaster, @7778666, @Dezmoh, @phuctohuu, @alexalvit, @cryptodexbest, @Kevin-Heleodoro, @glitch003, @harryho612, @PabloCastellano, @greenapple33, @Cryptomaster178, @BittuBabu1, @Freyja13, @oszdao, @Giridharilal, @0xelfarisy, @Ariffur, @dmytroprus, @Ford14, @Lana7kh, @Alifarghol1979, @onlinetipserYt, @Canawansansanf2, @Rekha4583, @f4l1pe, @cosmosfuture, @hiteshwadhwani, @itsrachelfish, @jele7ka, @Jony6196, @Diogomartf, @Poleschuka, @lalidammhotty, @d0wnlore, @omhaisora, @3aTkHuCb, @leninin, @Hendryfan, @shainaanum, @Giaphat1983, @Pilgrim71, @SatiaLee, @ducatedxz, @andreujuanc, @cowboyedition, @gustavolaux, @sriharshasaswath, @Vpum, @angelisaiarasi, @dappconsulting, @entueradigital, @byrd999, @yenisey, @thanhthao864, @amintajy2, @Ademidun007, @Nguyenngoc0810, @neatonk, @Kryptonplanet1, @Dim2013, @Acc3ssD3n13d, @YoonA747, @chenlintiny, @fosterpari, @dalu19, @Visentes, @agrozold, @Naxsun, @JaniAnttonen, @vanthang84, @ifir3, @ghjrdfDianaeagle, @unbanksytv, @raynemang, @koiking2018, @0xnth, @RomaWise, @youfoundron, @LarsHetfield, @Cryphub, @langipas122, @Hawkice, @mistricky, @TuanGu8, @DAO-collab, @daikiojm, @sunukhwang, @drewcook, @awhink17, @gajanand200, @ghannu786, @yhoungdev, @AlekseyURP, @manipulation44, @denybrv, @chienct2, @MarkZa007, @Kinguyen, @makstravel, @demiaaaaan, @blackid9, @synxero354, @yasmuru, @yasnakhodapanah, @ericlinML, @dotcoin2021, @silva0066, @jdkhp, @ozyman42, @testtk1, @cvrsor, @0xzoz, @michaelmooree, @Schreibmaschinespricht, @n37r09u3, @deshchoinakshe, @kris2210, @Delegat43, @blandupon, @daminasaws, @tucoin777

**Comment by lindembergandrade** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Sreerag-ibtl, @milancermak, @obatirou, @eddiehazel, @taramakage, @jerod-estapa, @vvinteresting, @leovct, @suicide, @cosmix, @AgoL5866, @victorelec14, @ckoopmann, @EpicLiem, @drunaar, @Dawimpy, @atshelchin, @BasixKOR, @0xOsiris, @refl3ction, @0x1un, @kannishk, @iFrostizz, @Starflower8, @aiportal, @ncitron, @5l1v3r1, @zees-dev, @0x0elliot, @stingzheng, @shresthagrawal, @datradito, @alureon, @ntrippar, @anthonyoliai, @kolyasapphire, @JP-Ellis, @meowyx, @mnuestc, @AlexanderDickie, @ccding, @HusseinLezzaik, @melekes, @zsluedem, @ehart004, @YeeJiaWei, @izqui, @toxotguo, @ArunSankarKs, @quangkeu95BinaryBar, @arbal, @popzxc, @chirag-bgh, @developerworks, @vyhisper, @Cionn3, @canghai118, @Moataz-E, @bongkarchip070890, @ttarsi, @JussaMouse, @gulitsky, @dsbrgg, @mdhash, @psushi, @p-r-i-t-h-v-i, @jaybuidl, @skynetcap, @roessland, @sslime336, @chixiaowen, @kirkdurgwillyk, @cp-juilpark, @inaridiy, @epociask, @valo, @wiasliaw, @Kayryu, @nuts-rice, @PeakyCryptos, @sarra-f, @8272, @vahid9000, @hoangph271, @dekz, @PaulRBerg, @syphrpunk, @iayanami, @evilakela, @hzqd, @QiangL, @hinryd, @qqil, @supleed2, @syjn99, @DividesZero, @jakubgs, @maniac1122, @yokiyokxriffus, @kylehowells, @MrMineev, @rhacker, @Lev1ty, @zaqk, @epappas, @percojazz, @codecontinuously, @akhilesh-w, @0xqibing, @AmanGotchuParadigm, @jaxonly, @revl, @AustinGreen, @valentynkvasov, @savvycraze, @EnoRage, @liangjh, @X140Yu, @NotJeremyLiu, @ccyanxyz, @stephenlacy, @hjioo74, @Fineas02, @distracted-kare, @feepwang, @GaFeFi, @pplanel, @lightclient, @autopaca, @Olyno, @TheArhaam, @ffrizzo, @timoa, @gunnigylfa, @amintalebi, @dannyp777, @agostbiro, @DaMandal0rian, @keroro520, @senthil28, @FredCoen, @aldoborrero, @v4lproik, @divineniiquaye, @Babanfarhan, @BlackNurse, @jimmygchen, @danielzhou82

**Comment by GTMany** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
zhulin0001, @Butynskyy, @Rangoscq, @surajj108, @montycheese, @0xMario27, @podiumdesu, @Hosseinom, @kako1357, @DIMCHERRY, @DrDen75, @SAMIZ111, @chad-js, @hroohbakhsh, @rezalakzaeii, @blackdoc111, @duleBLN, @DFA5, @ESHULSE9, @peakbolt, @pelakee13, @dadlessnsad, @medgyek, @yogiartnft, @Woasmahdi, @cheetahir, @bmasoudtc, @cryptosolutioner, @FiatPrint, @TaliaKaza, @xuan-io, @zrep1953, @bercortex, @realknown, @saeid7188, @pouyano, @BillGatesIII, @hojimxc, @maie880, @Ahmadzhd, @Chenxinjie65, @Shankusu993, @ONSENFOUEN, @drdfrink, @aytanet, @Sayfayguy, @Vadim535, @unbalancedparentheses, @naflan222, @zeuslionVhdeveth, @Swishified, @irizzzzz, @getoffers, @mostafapno, @jcurbelo, @Creative235, @ziljah, @LatifCrypto, @ALEKS5858, @Forbytex, @pokorb428, @rrm5863, @mlx72, @italoag, @haxshad, @mehmetalikuyucu, @IgorP04, @taempark, @Nazaninghnik, @liuyunsuixin, @ebihoseini, @aytamehd, @D-lyw, @davud1371, @tarhvaareh, @bahramgoz, @un9oo, @atapin, @Nikiforrovv, @nickvoronoov, @K-tabaki, @ilyasbo, @AbdelStark, @pantea1104, @ifls, @EG-easy, @delannoykurt, @josebernalte, @osmamad78, @ValeriyCrypt, @Yanatolochiy, @FredericaHart, @blackestwhite, @martinbaca1993, @nili1tomo, @iavl, @puntacana5, @pawpawya, @behnam12250x4r45h, @huguojunsy, @pouyano, @isabellewis262, @Rezaci02, @pour1234, @Bebolias, @nila-max, @anylots, @Ivashura93, @N4vid, @KimberleySonmerfield, @yocryptooooooo, @ThiagoJaweb, @zeuslion, @NadinkakS, @sfter, @lench1k-ok, @snmousavii, @wangwei2398, @fxp5yqb3, @mahan1397rahimi, @EmadAttarzadeh, @Drunkensai, @zer0cache, @Miladbazargan, @Bullcrypto89, @mamad219, @fathikhalil, @reza1001427, @Rubenaco, @atash1997, @Marg0pol0, @GrantStenger, @JGalbss, @Bernardsnow2002, @Sophia42011, @rampiro, @BitPan, @amir77137715, @shangcheng515, @dreamph, @matildameta, @dhelbegor, @esmaeil87, @sobhan9335, @lena-li2, @mousavi1356, @reyhanekamaeii, @Mahdi0905

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
xbj137661413, @cainiaocome, @weebi, @guangnaoke, @liu-yihong, @malymal, @AvichalChadha, @kentuckleberry, @cmdplusr, @Nightmare-Serene, @gjvandijk, @Ssunnyy, @felixlberg, @chenxiqiyuan, @wojtek2kdev, @neederhow, @SNAILTHELAZY, @longlive77, @liy05, @AsakuraMizu, @tony-xsr, @EmergentOrder, @akannke, @spalger, @thekalinga, @luda820804, @iaurg, @liesauer, @shokosanma, @alanmore231, @bgagan911, @3bf1114a986ba87e, @arbal, @goga-m, @1111Sirius1111, @ricardocostaarchm, @Erth616, @humonidtyphoon, @Jesn, @bourbakiN97, @muhammedsaid, @sulsoltanoff, @T1nFu, @jvmkit, @primus115, @enider, @esengine, @NayLinHtet4942, @Siss3l, @turtlebayjaizhengyu1992, @extremecoders-re, @dagmawibabi, @MustardseedX, @Izrab, @cowgirl6, @bigcyy, @DZL1943, @alehpineda, @podwodny, @neonalton, @h-s123, @daniodio, @PresleyHank, @s-and-t, @francisjsun, @knightop, @tulya409, @jeanbaptisteclemens, @krisl, @rkaelle, @Dginozator, @hissssst, @Heartnett, @Leslie-LIUU, @ccavxx, @molney239, @MoeruIshiki, @dnbrakk, @Shelob9, @qiugh, @ZechariahZheng, @raven4752, @weideguo, @kirollos91, @sailxjx, @kerryvernebegeman, @Cavefishy, @Yemaoxin, @mbledkowski, @ForsakenDurian, @pyronn, @GavinXF, @Teddycyber, @romainmoranges, @ClarePhang, @AlexANSO, @ahmeticat, @RtYkk, @FrankCCCCCCknightX, @wlabatey, @nodewey, @afshar-mohammad, @Hoku3, @TOMB-RIDER, @lazierhk, @smallverse, @rwbaumg, @xbee, @Bisquick69, @zxw4241, @ichiki, @nijatjafarov, @jniyn, @MlightShadow, @0x0005, @NeverKnowsTomorrow, @visinsight, @ah06, @xingkong2020, @DCjanus, @syncguol, @cavearr, @dustTx, @hjh010501, @doroshroman, @angelisochoa, @GuangdaJi, @remixer-dec, @swift1911, @hermitBits, @liuhaoXD, @r3shahbazi, @1024829326, @liwenzheng, @Iardo, @wayne2006, @NKID00, @ntzw, @kroppt, @xiexinyu-tech, @MichaelNasta, @Ratizux, @Joshua-chou, @Microwave22, @1109812950, @Alexei007, @hamedzurat, @DroidZed

**Comment by n1md7** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
MikhailoPro, @sebkys, @keepyourlightson, @rezha777, @infographie35, @alexisCode50, @dipugaa1, @dhjh1024, @sunweidongdong, @CryptoBikashAirdrop, @BillyRae, @abedfele, @alboairdrop, @sonnet014, @kmni91, @0x456ff3, @newindia1, @break199, @walleehe, @Gabnasyrov, @pedrosimoes679, @efenomeno, @Reza941, @wazirr155, @Kaewnguyen, @kimanbn, @hanafi0509, @cagataygoktepe, @AnashkinK, @Vladon773, @Zeeshan-2k1, @AGRime, @Kl0x2023, @ChristianM910, @gold3son, @Burak35Smoke, @farseatrade, @chrisfyk, @rivvnansld, @ChitrakshEastman, @xx666888, @muhuo2024, @mehdi2038, @Shohidul6699, @hadbhr, @humen86, @KodockOne, @shivamk89, @ssss12315, @lanqyjohnybitcoin, @Bmunizz, @cubanmicrowave, @achamaru1, @jalahong, @changkaixuan31, @humblemee, @opensourcedigest, @txzx456, @LDavila30, @xiaofeilong66, @onderfehmi, @DanielJD1216, @xiaohuolv, @wahyudinqimimz, @hamed-mn, @starpause, @Gmetaverse, @Mooon12342, @Ayugaps, @wshuaiwong2, @Poconhub, @bockbockbock3, @0x7673, @w22py, @nbgoku, @icezaland014, @Justice-hub, @cymeow, @movieperusal, @tofiquedurrani, @fengmolly888, @PunkCrow, @redhead-sensual, @sharpela, @xulanjin, @tzedonn, @kimphatxuan1985, @StasMexico, @jonnikrich, @Suko1, @RihanaDiario, @kdivus, @Grainey, @jinna520, @tax0951, @notacoolguy, @dgam777, @WRonim, @abagaillove1314henrycuong12, @xuansthien, @anandatwit, @chali1213, @Addison1244, @skyhighbirdfly, @xteemshara, @GoGucci, @quyenngo132, @mikecoburn, @koalamiguel, @Jy729, @Georgeanna9448, @brettwillis, @KimonoRed, @bibiqu, @147976780, @VVladyslav31, @robbieshadow, @mi2valley, @pancopa, @miguelgaton, @huuyafwww, @Hoangleebtc, @maksim0123456, @dongguaguaguagua, @feizaitianji, @Zoobebah, @Marjijoos, @unreachable0101, @zhangshilei3492, @IvanOrtiz64, @LouErGou, @soulgone, @violetaman, @misochan7, @0x8488, @abhi12216, @bengbuzhule666, @Kant-Bellamy, @Allreasons, @qweQWER123, @imad1977, @pedrosimoes679, @ling3677, @SuperHolicxyz, @pinkcaptain, @0x113838, @sidneyakpaso, @Alex065076069088
