### ISSUE TITLE
How to know if it is decompiling?

### ISSUE THREAD

**Issue by Jimster4312** [extremecoders-re/python-snippet-decompiler#6]
Is there anyway to know that it is decompiling?
I have a quite large file and I'm not sure if it is decompiling (does it decompile it all at once or line by line?)

For reference the `<module>` size is `19210` and the bytecode output file is over `45000` lines

Is there any message or popup I'm missing that shows an error or that its decompiling?

**Comment by extremecoders-re** [comment]
There is no visual indicator at the moment to know when a decompile is in progress but generally if there is no output within a few seconds means the pycdc process has crashed. To cross check you can try decompiling the .pyc file directly with pycdc.

**Comment by Jimster4312** [comment]
Does pycdc decompile from bytecode? I though it only decompiled from file, and that doesn't work for my file since it includes the `BEFORE_WITH` opcode. I tried to edit the original build but it just kept crashing.

**Comment by Jimster4312** [comment]
Alrighty thanks!
Will do some testing

**Comment by extremecoders-re** [comment]
> Does pycdc decompile from bytecode? I though it only decompiled from file, and that doesn't work for my file since it includes the `BEFORE_WITH` opcode. I tried to edit the original build but it just kept crashing.

Yes pycdc does decompile from bytecode. As not all python opcodes specially the newer ones are supported by pycdc, the snippet decompiler tries to work around the issue by selectively decompiling bytecode instructions. Internally it creates a code object with the instructions from the input box, creates a pyc file out of it and passes that to pycdc. Unfortunately pycdc can crash still or provide erroneous output especially if the provided list of instructions is invalid (when taken in a standalone context) or has unresolved control flow. In such cases better to provide a small listing of instructions than a huge code block.

snippet-decompiler is merely a tool to assist manual decompiling. If you already can hand decompile pyc files this tools aims to speed up the process. For example, if you have a long list of instructions which assigns values to variables, or perform computations and such and you already known how to manually decompile those but would take a lot of time, you can use snippet decompiler on it to speed up your work.
